### ISSUE TITLE
Don't see an initialize function

### ISSUE THREAD

**Issue by franktinsley** [ThisNetWorks/iVidCapPro#12]
Hey guys, this plugin is absolutely saving my life right now!
Just trying to find how to get the whole record system to initialize before I call iVidCapPro.BeginRecordingSession() because when I call it for the first time, the initialization causes some pretty bad performance issues when it runs on top of everything else I have going. The first captured video has about 3 seconds of frozen video while unity cleans up memory.
Thanks again guys!!

**Comment by ThisNetWorks** [comment]
That's great to hear it's helping you.

There is no specific initialization method, BeginRecordingSession() should be what you're using.

I'm surprised that you're getting frozen video. How much do you have going on in your scene before you start your recording? Is it started from a Start monobehaviour, or is it something you start after other events have run.

I have some very heavy animations that startup before recording with iVidCapPro and have no problems with frozen video, or initializing it from Start().

I suspect it maybe unity that is misperforming, and not giving iVidCapPro the frames it wants in a timely fashion.

What is unity cleaning up? Unused assets? It's worth calling Resources.UnloadUnusedAssets (think that's the method, my memory fails me right now), at the end of the scene change, before you startup the scene with iVidCapPro in it - that's helped us a lot with memory issues, to the point where we've been able to get everything running properly on a very low memory ipod touch.

If that doesn't help, can you attach the xcode logs, and we'll have a look at what it's cleaning up.
