### ISSUE TITLE
Cloud Compatibility?

### ISSUE THREAD

**Issue by eblabs** [ThisNetWorks/iVidCapPro#14]
Hi, just a question. 

Does this support cloud build? I see that there are some additional xcode files that need to be installed, so I wasn't sure if this would work on the build cloud. 

Thanks for any thoughts.

**Comment by ThisNetWorks** [comment]
Hi,

I haven't built it with cloud, however there shouldn't be any issues. The xcode library .a file is included as part of the unity code folder, which will be part of the build going up to cloud.

The addition xcode files you're seeing are for use if you want to rebuild the .a library file - and then include it in your normal Unity distribution.

**Comment by eblabs** [comment]
Awesome, thanks!!
