### ISSUE TITLE
iVidCapPro_PostBuild getting mixed up about versions (and Failing)

### ISSUE THREAD

**Issue by peteski** [ThisNetWorks/iVidCapPro#16]
Hi there,

I ran into an issue where the post build was failing (trying to find "appcontroller.mm"). Turns out the post process check for Unity version was thinking it was 4.2 because my Unity version is 2017.4.2f2  :)
I just commented out those checks so it uses the latest version and it seems to be working now.
Just thought I'd let you know. 
Thank you so much for putting this out there by the way!

Thanks,
Pete

**Comment by ThisNetWorks** [comment]
Thanks Pete, yes the fixes for that are also on the develop branch. Must really get a new release out! Cheers
