### ISSUE TITLE
combining with Amplify LUT Pack

### ISSUE THREAD

**Issue by ghost** [ThisNetWorks/iVidCapPro#3]
Is there anyway to record camera effect using Amplify LUT Pack?
Please help and thanks.

**Comment by Akevlam** [comment]
I think this should be possible.  Have you tried adding the iVidCapProVideo component below the the Amplify LUT component on the camera? The effects on the camera should be evaluated in top to bottom order.

**Comment by ghost** [comment]
oh, it works now
thanks
:)
